### ISSUE TITLE
Entity framework support

### ISSUE THREAD

**Issue by BorisGerretzen** [dariogriffo/Nordigen.Net#15]
I think the response classes cannot work as EF entities because almost all properties only have getters. By adding a private setter the functionality stays the same but entity framework will be able to map the properties. If you agree with this I can submit a PR for the feature.

If there is another way to do this without changing the response models, let me know! I am new to EF so excuse me if this is a dumb issue.

**Comment by dariogriffo** [comment]
Hi @BorisGerretzen, thanks for this, I would decline this, and the reasons are
- you should not be able to change the response, this allows to unexpected behaviour down the road and bugs. Immutability is a great friend in a developers life!
- you would like to have separated layers in the app, and don't tie your database models to your Open Banking model, you may want to change the provider to let's say TrueLayer, and their model might be slightly different. 
Each layer should have their own models and you can use something like [Automapper](https://automapper.org/) to make the mapping seamlessly between your layers.
Hope this makes sense

**Comment by BorisGerretzen** [comment]
Hi, I understand that immutability is nice to have but by using private set it is only mutable from the class itself, from outside it is still mutable.

I get your point about the layers though, I will try Automapper. Thanks for your time!
