### ISSUE TITLE
proprietaryBankTransactionCode is unused

### ISSUE THREAD

**Issue by BorisGerretzen** [dariogriffo/Nordigen.Net#16]
`proprietaryBankTransactionCode` is an argument in the constructor of `Transaction` but there is no property for it in the class and the parameter is not used in the constructor.

**Comment by BorisGerretzen** [comment]
More items from the list [here](https://nordigen.com/en/docs/account-information/output/transactions/) are also missing.

**Comment by dariogriffo** [comment]
Want to open a PR?

**Comment by BorisGerretzen** [comment]
Of course, I'll start on it tomorrow.

**Comment by BorisGerretzen** [comment]
In that documentation it says that a lot of the fields that are currently not nullable are optional. I assumed the TransactionId would be present in every transaction but it is not, it depends on which bank you use. Should I make the fields that are marked 'optional' in the documentation nullable?

I don't know why the API is so messy, only 1 property is actually mandatory for a transaction and that is the amount, all other properties are optional.

**Comment by dariogriffo** [comment]
> I don't know why the API is so messy, only 1 property is actually mandatory for a transaction and that is the amount, all other properties are optional.

This is the reason I'm not actively involved. The nordigen team was not responsive, the docs are not clear.
Sorry for this

**Comment by BorisGerretzen** [comment]
Yeah I get what you mean. I found [this](https://docs.google.com/spreadsheets/d/11tAD5cfrlaOZ4HXI6jPpL5hMf8ZuRYc6TUXTxZE84A8/edit#gid=0) google sheet that's referenced from their documentation page. I dont know why `proprietaryBankTransactionCode` has two columns with different values here? I also do not understand why they have an internal transaction id field that Nordigen themselves give to transactions, but then it's not available for all banks? From what I can see the other people that are developing clients for Nordigen's API are struggling with the same issues.

I will make the optional fields nullable and let the end user (also me) figure out how to actually get a unique ID for a transaction haha.

**Comment by BorisGerretzen** [comment]
Can you check my PR? I have left out some stuff that is unclear from the documentation. I exchanged some emails with nordigen but they haven't responded in a while.
